name:                emd
version:             0.1.4.0
github:              "mstksg/emd"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md
- test-data/*

# Metadata used when publishing your package
synopsis:            Empirical Mode Decomposition and Hilbert-Huang Transform
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/emd#readme>
tested-with:         GHC >= 8.2

dependencies:
- base >= 4.10 && < 5
- containers

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wcompat


library:
  source-dirs: src
  other-modules:
  - Numeric.EMD.Internal.Tridiagonal
  - Numeric.EMD.Internal.Extrema
  dependencies:
  - binary
  - data-default-class
  - finite-typelits
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - transformers
  - typelits-witnesses
  - vector
  - vector-sized

tests:
  emd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - emd
