name:                emd
version:             0.2.1.0
github:              "mstksg/emd"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"

extra-source-files:
- README.md
- CHANGELOG.md
- test-data/*

# Metadata used when publishing your package
synopsis:            Empirical Mode Decomposition and Hilbert-Huang Transform
category:            Math

description: |
  Empirical Mode decomposition and Hilbert-Huang Transform in pure
  Haskell.

tested-with:         GHC >= 8.4

dependencies:
- base >= 4.11 && < 5

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wcompat
- -Werror=incomplete-patterns


library:
  source-dirs: src
  other-modules:
  - Numeric.EMD.Internal
  - Numeric.EMD.Internal.Extrema
  - Numeric.EMD.Internal.Pipe
  - Numeric.EMD.Internal.Tridiagonal
  - Numeric.HHT.Internal.FFT
  dependencies:
  - array
  - binary
  - carray
  - conduino
  - containers
  - data-default-class
  - deepseq
  - fft
  - finite-typelits
  - free
  - ghc-typelits-knownnat
  - ghc-typelits-natnormalise
  - transformers
  - typelits-witnesses
  - vector
  - vector-sized >= 1.4

tests:
  emd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - containers
    - emd
    - ghc-typelits-knownnat
    - ghc-typelits-natnormalise
    - hedgehog
    - statistics
    - tasty
    - tasty-hedgehog
    - tasty-hunit
    - typelits-witnesses
    - vector
    - vector-sized

benchmarks:
  emd-bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - emd
    - ghc-typelits-knownnat
    - mwc-random
    - vector
    - statistics
    - vector-sized >= 1.4
